# Generated by Django 4.2.3 on 2023-07-17 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_categorias_nombre_subcategorias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorias',
            name='categoria',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.categorias', verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='subcategorias',
            name='nombre',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Nombre'),
        ),
    ]
