# Generated by Django 4.2.3 on 2023-07-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_subcategorias_categoria_alter_subcategorias_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
