# Generated by Django 4.2.3 on 2023-07-18 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_productos_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='imagen',
            new_name='image',
        ),
    ]
