# Generated by Django 4.2.3 on 2023-07-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_rename_imagen_productos_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategorias',
            name='nombre',
        ),
        migrations.AddField(
            model_name='subcategorias',
            name='sub_categoria',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='image',
            field=models.ImageField(default=None, upload_to='productos'),
        ),
    ]
