# Generated by Django 4.2.3 on 2023-07-24 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_alter_productos_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorias',
            name='categoria',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.categorias', verbose_name='Nombre'),
        ),
    ]
