# Generated by Django 4.2.3 on 2023-07-24 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_alter_subcategorias_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre_categoria',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.categorias'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre_subcategoria',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.subcategorias'),
        ),
    ]
