# Generated by Django 4.2.3 on 2023-07-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutmemodel_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutmemodel',
            options={'verbose_name': 'Presentación de la empresa', 'verbose_name_plural': 'Presentaciones de la empresa'},
        ),
        migrations.AlterField(
            model_name='aboutmemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
